services:
  publication-scheduler-web:
    container_name: publication_scheduler_web
    build:
      context: .
      dockerfile: Dockerfile
      target: local
    ports:
      - "${PUBLICATION_SCHEDULER_WEB_PORT}:3000"
    volumes:
      - .:/publication-scheduler-web
    depends_on:
      - postgres-publication-scheduler-web
    tty: true

  postgres-publication-scheduler-web:
    container_name: postgres_publication_scheduler_web
    image: postgres:15-alpine
    ports:
      - "${DATABASE_PORT}:5432"
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
